---
 - name: "Create Mongo User"
   mongodb_user: 
     login_host: "{{ lookup('env','DB_HOST') }}"
     login_user: "{{ lookup('env','DB_USERNAME') }}"
     login_password: "{{ lookup('env','DB_PASSWORD') }}"
     login_database: "admin"
     database: "{{ item.value.database }}"  
     user: "{{ item.value.username }}" 
     password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}" 
     state: present
     update_password: on_create
     roles:
       - db: "{{ item.value.database }}" 
         role: "{{ item.value.permission }}"
 - copy: 
       content: "DB_USER={{ item.value.username }}\nDB_DATABASE={{ item.value.database }}\nDB_HOST={{ lookup('env','DB_HOST') }}\nDB_PASSWORD={{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}\nDB_PERMISSION={{ item.value.permission }}\nDB_TYPE='mongodb'"
       dest: "./mongodb_secret.env" 
 - name: Set Path
   set_fact:
     user_path: "users/"
   when: not item.value.app_user
 - name: Set app path
   set_fact:
     app_path: "{{ item.value.database }}-{{ syslevel }}/"
   when: not item.value.app_user
 - name: "Upload secret to s3"
   command: "aws s3 cp ./mongodb_secret.env s3://kf-538745987955-us-east-1-{{ syslevel }}-secrets/{{ user_path }}{{ item.value.username }}/{{ app_path }}mongodb_secret.env"
   when:  syslevel != "service"
 - name: "Upload secret to s3"
   command: "aws s3 cp ./mongodb_secret.env s3://kf-538745987955-us-east-1-dev-secrets/{{ user_path }}{{ item.value.username }}/{{ app_path }}mongodb_secret.env"
   when:  syslevel == "service"
 - name: "Upload secret to s3"
   command: "aws s3 cp ./mongodb_secret.env s3://kf-538745987955-us-east-1-qa-secrets/{{ user_path }}{{ item.value.username }}/{{ app_path }}mongodb_secret.env"
   when: syslevel == "service"
